spring:
  application:
    name: orch-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/orch_demo?currentSchema=orch_demo
    username: postgres
    password: postgres


camel:
  rest:
    component: netty-http
    host: 0.0.0.0
    port: 9090
  springboot:
    main-run-controller: true

seda:
#  тонкая настройка потоков для каждого этапа
  endpointsThreads:
    init-route: 2
    handle-route: 5