spring:
  application:
    name: orch-demo


camel:
  rest:
    component: netty-http
    host: 0.0.0.0
    port: 9090
  springboot:
    main-run-controller: true

seda:
#  тонкая настройка потоков для каждого этапа
  endpointsThreads:
    init-route: 2
    handle-route: 5